[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
solc_version = "0.8.22"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
celo = "${CELO_RPC_URL}"
alfajores = "${ALFAJORES_RPC_URL}"

[etherscan]
celo = { key = "${CELOSCAN_API_KEY}", url = "https://api.celoscan.io/api" }
